### PR TITLE
compiler(arm64): fixes overflow in huge executable relocations

### LINKED ISSUE #2158: compiler(arm64) overflow in call relocations
**Describe the bug**

A wasm module that was being compiled and instantiated with wazero 1.6.0 successfully now segfaults with version 1.7.0.

**To Reproduce**
I am building my own experimental tool that embeds wazero for supporting wasm. Here is a link to the wasm file I was testing with:
https://github.com/davidmdm/flights/releases/download/v0.0.0-yokecd-test/pg.wasm

This module is an executable that should output some JSON to stdout.

This is the code I use to intantiate it:

```go
package wasi

import (
	"bytes"
	"context"
	"crypto/rand"
	"fmt"
	"io"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/imports/wasi_snapshot_preview1"

	"github.com/davidmdm/x/xerr"
)

func Execute(ctx context.Context, wasm []byte, release string, stdin io.Reader, args ...string) (output []byte, err error) {
	cfg := wazero.
		NewRuntimeConfig().
		WithCloseOnContextDone(true)

	// Create a new WebAssembly Runtime.
	wasi := wazero.NewRuntimeWithConfig(ctx, cfg)
	defer func() {
		err = xerr.MultiErrFrom("", err, wasi.Close(ctx))
	}()

	wasi_snapshot_preview1.MustInstantiate(ctx, wasi)

	// Because we are running a binary directly rather than embedding in an application,
	// we default to wiring up commonly used OS functionality.
	mod, err := wasi.CompileModule(ctx, wasm)
	if err != nil {
		return nil, fmt.Errorf("failed to compile module: %w", err)
	}

	var (
		stdout bytes.Buffer
		stderr bytes.Buffer
	)

	moduleCfg := wazero.
		NewModuleConfig().
		WithStdout(&stdout).
		WithStderr(&stderr).
		WithRandSource(rand.Reader).
		WithSysNanosleep().
		WithSysNanotime().
		WithSysWalltime().
		WithArgs(append([]string{release}, args...)...)

	if stdin != nil {
		moduleCfg = moduleCfg.WithStdin(stdin)
	}

	if _, err := wasi.InstantiateModule(ctx, mod, moduleCfg); err != nil {
		details := stderr.String()
		if details == "" {
			details = "(no output captured on stderr)"
		}
		return nil, fmt.Errorf("failed to instantiate module: %w: stderr: %s", err, details)
	}

	return stdout.Bytes(), nil
}
```

**Expected behavior**

I expect the wasm file to be executed without segfaults, and to produce the same output as wazero 1.6.0

**Screenshots**
image

**Environment (please complete the relevant information):**
- go version go1.22.1 darwin/arm64
- wazero Version: 1.7.0
- Host architecture: arm64

**Additional context**

### PR DESCRIPTION
**Pull request by mathetake**
Obviates https://github.com/tetratelabs/wazero/pull/2169 and fixes #2158

### CODE REVIEW

**Comment by mathetake** [comment]
needs to backfill tests and then ready to go

File: internal/engine/wazevo/backend/isa/arm64/machine_relocation.go [hunk 1]
```diff
@@ -1,27 +1,63 @@
...
+
+	maxUnconditionalBranchOffset = maxSignedInt26 * 4
+	minUnconditionalBranchOffset = minSignedInt26 * 4
+)
+
+// CallTrampolineIslandInfo implements backend.Machine CallTrampolineIslandInfo.
+func (m *machine) CallTrampolineIslandInfo(numFunctions int) (interval, size int) {
+	// Always place trampoline in the middle of the range.
+	// TODO: precondition is that neither the trampoline size or a single function size is bigger than the range.
+	//	Add asserts to check this.
```
Comment (mathetake) [inline internal/engine/wazevo/backend/isa/arm64/machine_relocation.go:26]: todo tomorrow
