### PR TITLE
Complete bulk memory operations proposal

### LINKED ISSUE #321: Add opt-in support for post 1.0 bulk-memory-operations
Looks like Grain defaults to use bulk-memory-operations, though this can be disabled with `--no-bulk-memory` per https://github.com/grain-lang/grain/pull/819

Meanwhile, our crash isn't so pretty:

```
(41/323): invalid instruction 0xfc
```

cc @pims

### PR DESCRIPTION
**Pull request by mathetake**
This commit implements the rest of unimplemented instructions in the 
bulk-memory-operations proposal.

Notably, this adds support for `table.init`, `table.copy` and `elem.drop`
instructions toggled by FeatureBulkMemoryOperations.

Given that, now wazero has the complete support for bulk-memory-operations
proposal as described in https://github.com/WebAssembly/spec/blob/main/proposals/bulk-memory-operations/Overview.md

fixes #321

### CODE REVIEW

File: internal/wasm/binary/element_test.go [hunk 1]
```diff
@@ -0,0 +1,255 @@
...
+import (
+	"bytes"
+	"strconv"
+	"testing"
+
+	"github.com/tetratelabs/wazero/internal/testing/require"
+	"github.com/tetratelabs/wazero/internal/wasm"
+)
+
+func asNUllableIndex(v uint32) wasm.NullableIndex {
```
Comment (codefromthecrypt) [inline internal/wasm/binary/element_test.go:12]: maybe `uint32Ptr` to save wrapping? "nullable index" isn't terribly necessary in tests

File: internal/wasm/module.go [hunk 2]
```diff
@@ -577,6 +577,8 @@ func (m *Module) resolveFunction(moduleName string, f *FunctionInstance, funcIdx
 // See https://www.w3.org/TR/2019/REC-wasm-core-1-20191205/#binary-index
 type Index = uint32
 
+type NullableIndex *uint32
```
[the remark this answers is not in the document]
Comment (mathetake) [reply internal/wasm/module.go:580]: sg

File: internal/wasm/binary/element_test.go (hunk 1 above)
Comment (mathetake) [reply internal/wasm/binary/element_test.go:12]: works for me

**Comment by mathetake** [comment]
ok now intepreter passes https://github.com/WebAssembly/spec/blob/9b4d86fbcd3309c3365c8430a4ac5ef2126c43a8/test/core/bulk.wast on my local machine.. other spectests are conflated with ref type proposal (notable multi tables) so I will defer the spec test compatibility test to the ref type proposal impl later.

will do the JIT tomorrow

File: internal/integration_test/post1_0/bulk-memory-operations/spec_test.go [hunk 3]
```diff
@@ -17,23 +18,185 @@ func TestBulkMemoryOperations_JIT(t *testing.T) {
...
-// bulkMemoryOperationsWasm was compiled from testdata/bulk_memory_operations.wat
-//go:embed testdata/bulk_memory_operations.wasm
-var bulkMemoryOperationsWasm []byte
+var (
+	// bulkMemoryOperationsWasm was compiled from testdata/bulk_memory_operations.wat
+	//go:embed testdata/bulk_memory_operations.wasm
+	bulkMemoryOperationsWasm []byte
+	// tableCopyWasm was compiled from testdata/table_copy.wat
+	//go:embed testdata/table_copy.wasm
+	tableCopyWasm []byte
```
Comment (mathetake) [inline internal/integration_test/post1_0/bulk-memory-operations/spec_test.go:39]: note: these are derived from https://github.com/WebAssembly/spec/blob/9b4d86fbcd3309c3365c8430a4ac5ef2126c43a8/test/core/bulk.wast

File: internal/wasm/func_validation.go [hunk 4]
```diff
@@ -759,7 +759,7 @@ func (m *Module) validateFunctionWithMaxStackValues(
 				var params []ValueType
 				switch miscOpcode {
 				case OpcodeMiscMemoryInit, OpcodeMiscMemoryCopy, OpcodeMiscMemoryFill, OpcodeMiscDataDrop:
```
Comment (codefromthecrypt) [inline internal/wasm/func_validation.go:761]: quick comment above here and elsewhere which feature/release these are about as it is confusing since Wasm mixes things so much.

Ex. // Handle opcodes added in bulk-memory-operations/WebAssembly 2.0

File: internal/wasm/instruction.go [hunk 5]
```diff
@@ -229,6 +229,22 @@ const (
 	OpcodeF32ReinterpretI32 Opcode = 0xbe
 	OpcodeF64ReinterpretI64 Opcode = 0xbf
 
+	// OpcodeRefNull pushes a null reference value whose type is specified by immediate to this opcode.
+	// This is defined in the reference types proposal, but necessary for bulk-memory proposal as well.
+	//
+	// Currently only supported in the constant expression in element segments.
+	OpcodeRefNull = 0xd0
+	// OpcodeRefIsNull pops a reference value, and pushes 1 if it is null, 0 otherwise.
+	// This is defined in the reference types proposal, but necessary for bulk-memory proposal as well.
```
Comment (codefromthecrypt) [inline internal/wasm/instruction.go:238]: please use reference-types when discussing the proposal, for find purposes. Also, we should be using the symbols where possible I think. Ex FeatureBulkMemory

File: internal/wasm/interpreter/interpreter.go [hunk 6]
```diff
@@ -535,6 +536,20 @@ func (me *moduleEngine) Name() string {
 	return me.name
 }
 
+// CreateFuncElementInstnace implements the same method as documented on wasm.ModuleEngine.
+func (me *moduleEngine) CreateFuncElementInstnace(indexes []*wasm.Index) *wasm.ElementInstance {
```
Comment (codefromthecrypt) [inline internal/wasm/interpreter/interpreter.go:540]: spelling here and godoc

File: internal/wasm/interpreter/interpreter.go [hunk 7]
```diff
@@ -1738,6 +1754,33 @@ func (ce *callEngine) callNativeFunc(ctx context.Context, callCtx *wasm.CallCont
 				}
 			}
 			frame.pc++
+		case wazeroir.OperationKindTableInit:
```
Comment (codefromthecrypt) [inline internal/wasm/interpreter/interpreter.go:1757]: mention where these opcodes are from or double space around "// Handle instructions added in FeatureBulkMemoryOperations and WebAssembly 2.0"

File: internal/wasm/jit/compiler.go [hunk 8]
```diff
@@ -357,4 +357,19 @@ type compiler interface {
 	//
 	// https://www.w3.org/TR/2022/WD-wasm-core-2-20220419/appendix/changes.html#bulk-memory-and-table-instructions
 	compileMemoryFill() error
+	// compileTableInit adds instructions to perform operations corresponding to the wasm.OpcodeTableInit instruction in
+	// the bulk-memory-operations proposal.
```
Comment (codefromthecrypt) [inline internal/wasm/jit/compiler.go:361]: I know I started this, but we have constants so we can probably use them to help centralize docs. Ex. 
```suggestion
	// wasm.FeatureBulkMemoryOperations.
```

then if that symbol already has the link you don't need to repeat it under!

File: internal/wasm/jit/engine.go [hunk 9]
```diff
@@ -110,11 +110,14 @@ type (
 		// codesElement0Address is &moduleContext.engine.codes[0] as uintptr.
 		codesElement0Address uintptr
 
-		// typeIDsElement0Address holds the &ModuleInstance.typeIDs[0] as uintptr.
+		// typeIDsElement0Address holds the &ModuleInstance.TypeIDs[0] as uintptr.
 		typeIDsElement0Address uintptr
 
-		// dataInstancesElement0Address holds the &ModuleInstance.dataIntances[0] as uintptr.
+		// dataInstancesElement0Address holds the &ModuleInstance.DataIntances[0] as uintptr.
```
Comment (codefromthecrypt) [inline internal/wasm/jit/engine.go:116]: spelling

File: internal/wasm/jit/engine.go [hunk 10]
```diff
@@ -288,7 +293,14 @@ const (
 	// Offsets for Go's interface.
 	// https://research.swtch.com/interfaces
 	// https://github.com/golang/go/blob/release-branch.go1.17/src/runtime/runtime2.go#L207-L210
-	interfaceDataOffset = 8
+	interfaceDataOffset   = 8
+	interfaceDataSizeLog2 = 4
```
Comment (codefromthecrypt) [inline internal/wasm/jit/engine.go:297]: comment why

File: internal/wasm/jit/engine.go [hunk 11]
```diff
@@ -288,7 +293,14 @@ const (
...
+
+	// Consts for DataInstance.
+	dataInstanceStructSize = 24
+
+	// Consts for ElementInstance.
+	elementInsanceStructSize = 32
```
Comment (codefromthecrypt) [inline internal/wasm/jit/engine.go:303]: spelling

File: internal/wasm/jit/engine.go [hunk 12]
```diff
@@ -501,8 +513,23 @@ func (me *moduleEngine) Name() string {
 	return me.name
 }
 
+// Call implements the same method as documented on wasm.ModuleEngine.
```
Comment (codefromthecrypt) [inline internal/wasm/jit/engine.go:516]: c&p
```suggestion
// CreateFuncElementInstance implements the same method as documented on wasm.ModuleEngine.
```

File: internal/wasm/jit/engine.go [hunk 13]
```diff
@@ -501,8 +513,23 @@ func (me *moduleEngine) Name() string {
...
+	}
+	return &wasm.ElementInstance{
+		References: refs,
+		Type:       wasm.RefTypeFuncref,
+	}
+}
+
 // Call implements the same method as documented on wasm.ModuleEngine.
 func (me *moduleEngine) Call(ctx context.Context, callCtx *wasm.CallContext, f *wasm.FunctionInstance, params ...uint64) (results []uint64, err error) {
+	// runtime.Breakpoint()
```
Comment (codefromthecrypt) [inline internal/wasm/jit/engine.go:532]:
```suggestion
```

File: internal/wasm/jit/jit_impl_amd64.go [hunk 14]
```diff
@@ -3657,6 +3774,42 @@ func (c *amd64Compiler) compileMemoryFill() error {
 	return nil
 }
 
+func (c *amd64Compiler) compileTableInit(o *wazeroir.OperationTableInit) error {
```
Comment (codefromthecrypt) [inline internal/wasm/jit/jit_impl_amd64.go:3777]: don't forget the boilerplate if any of this stuff is implementing an interface. if not, fine for no godoc, just seems like this is about an interface.

File: internal/wasm/jit/jit_impl_arm64.go [hunk 15]
```diff
@@ -2902,76 +2915,115 @@ func (c *arm64Compiler) compileMemoryInit(o *wazeroir.OperationMemoryInit) error
...
+			arm64ReservedRegisterForTemporary)
+		// [destinationOffset + (size.register)] = arm64ReservedRegisterForTemporary.
+		c.assembler.CompileRegisterToMemoryWithRegisterOffset(movInst,
+			arm64ReservedRegisterForTemporary,
+			destinationOffset.register, copySize.register,
+		)
 
-	c.markRegisterUnused(copySize.register, sourceOffset.register,
-		destinationOffset.register, dataInstanceAddr)
+		// Decrement the size coutner and if the value is still negative, continue the loop.
```
Comment (codefromthecrypt) [inline internal/wasm/jit/jit_impl_arm64.go:3018]:
```suggestion
		// Decrement the size counter and if the value is still negative, continue the loop.
```

**Review by codefromthecrypt — APPROVED** [review]
Epic. please in the PR description add a summary of anything interesting you found that others should know about. A brain dump in concise form may come in handy later!

**Comment by mathetake** [comment]
ok resolved all comments! merging!
