### PR TITLE
gojs/test: resolve race under scheduleTimeoutEvent

### LINKED ISSUE #992: flakey test: gojs Test_stdio_large
```
--- FAIL: Test_stdio_large (0.50s)
[34](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:35)
    require.go:312: expected "stderr 2097152
[35](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:36)
        ", but was "fatal error: malloc deadlock
[36](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:37)
        
[37](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:38)
        runtime stack:
[38](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:39)
        runtime.throw({0x6b9ce, 0xf})
[39](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:40)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1198 +0x7
[40](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:41)
        runtime.mallocgc(0x10, 0x42cc0, 0x1)
[41](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:42)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/malloc.go:972 +0xcf
[42](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:43)
        runtime.newobject(0x42cc0)
[43](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:44)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/malloc.go:1234 +0x4
[44](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:45)
        runtime.handleEvent()
[45](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:46)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/lock_js.go:238 +0x2
[46](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:47)
        runtime.sysReserve(0x0, 0x800000)
[47](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:48)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/mem_js.go:68 +0xe
[48](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:49)
        runtime.sysReserveAligned(0x0, 0x400000, 0x400000)
[49](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:50)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/malloc.go:805 +0x2
[50](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:51)
        runtime.(*mheap).sysAlloc(0x329700, 0x400000)
[51](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:52)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/malloc.go:698 +0x4f
[52](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:53)
        runtime.(*mheap).grow(0x329700, 0x122)
[53](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:54)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/mheap.go:1347 +0xa
[54](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:55)
        runtime.(*mheap).allocSpan(0x329700, 0x122, 0x0, 0x1)
[55](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:56)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/mheap.go:1179 +0x3b
[56](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:57)
        runtime.(*mheap).alloc.func1()
[57](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:58)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/mheap.go:913 +0x6
[58](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:59)
        runtime.systemstack()
[59](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:60)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_wasm.s:170 +0x2
[60](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:61)
        runtime.mstart()
[61](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:62)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_wasm.s:28
[62](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:63)
        
[63](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:64)
        goroutine 1 [running]:
[64](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:65)
        runtime.systemstack_switch()
[65](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:66)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_wasm.s:181 fp=0x42ace8 sp=0x42ace0 pc=0x13ac0000
[66](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:67)
        runtime.(*mheap).alloc(0x329700, 0x122, 0x1, 0x0)
[67](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:68)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/mheap.go:907 +0x2 fp=0x42ad30 sp=0x42ace8 pc=0x11750002
[68](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:69)
        runtime.(*mcache).allocLarge(0x350108, 0x244000, 0x0, 0x1)
[69](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:70)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/mcache.go:227 +0x9 fp=0x42ad90 sp=0x42ad30 pc=0x10ed0009
[70](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:71)
        runtime.mallocgc(0x244000, 0x0, 0x0)
[71](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:72)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/malloc.go:1088 +0x8f fp=0x42ae18 sp=0x42ad90 pc=0x10a4008f
[72](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:73)
        runtime.growslice(0x274c0, {0x500000, 0x1d0000, 0x1d0000}, 0x1d0001)
[73](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:74)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/slice.go:261 +0x83 fp=0x42ae68 sp=0x42ae18 pc=0x12c60083
[74](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:75)
        io.ReadAll({0xba820, 0x40c018})
[75](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:76)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/io/io.go:631 +0x7 fp=0x42aee0 sp=0x42ae68 pc=0x15530007
[76](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:77)
        github.com/tetratelabs/wazero/internal/gojs/testdata/stdio.Main()
[77](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:78)
        	/home/runner/work/wazero/wazero/internal/gojs/testdata/stdio/main.go:10 +0x2 fp=0x42af28 sp=0x42aee0 pc=0x1f2f0002
[78](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:79)
        main.main()
[79](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:80)
        	/home/runner/work/wazero/wazero/internal/gojs/testdata/main.go:40 +0x2a fp=0x42af88 sp=0x42af28 pc=0x1f34002a
[80](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:81)
        runtime.main()
[81](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:82)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/proc.go:255 +0x35 fp=0x42afe0 sp=0x42af88 pc=0x121f0035
[82](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:83)
        runtime.goexit()
[83](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:84)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_wasm.s:431 +0x1 fp=0x42afe8 sp=0x42afe0 pc=0x13d50001
[84](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:85)
        stderr 2097152
[85](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:86)
        "
[86](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:87)
        /home/runner/work/wazero/wazero/internal/gojs/misc_test.go:56
```

### PR DESCRIPTION
**Pull request by mathetake**
fixes #992

### CODE REVIEW

**Comment by mathetake** [comment]
ok verified that this works https://github.com/tetratelabs/wazero/actions/runs/4005901891/jobs/6876816405

File: internal/gojs/compiler_test.go [hunk 1]
```diff
@@ -96,6 +102,19 @@ func TestMain(m *testing.M) {
 		log.Panicln(err)
 	}
 
+	// In order to avoid race condition on scheduleTimeoutEvent, we need to set the memory max
+	// and WithMemoryCapacityFromMax(true) above.
+	// https://github.com/tetratelabs/wazero/issues/992
+	//
+	// TODO: Maybe add WithMemoryMax API?
```
Comment (codefromthecrypt) [inline internal/gojs/compiler_test.go:109]: We had something like this once, but I wonder if it would interfere with caching? Changing the max would be slightly different than the source wasm, where capacity is undefined in wasm anyway.

File: internal/gojs/compiler_test.go [hunk 2]
```diff
@@ -96,6 +102,19 @@ func TestMain(m *testing.M) {
...
+	parsed, err := binaryformat.DecodeModule(testBin, api.CoreFeaturesV2, wasm.MemoryLimitPages, false, false, false)
+	if err != nil {
+		log.Panicln(err)
+	}
+	parsed.MemorySection.Max = 1000
```
Comment (codefromthecrypt) [inline internal/gojs/compiler_test.go:114]: This is a large amount of memory, and noting the issue number is nice, but maybe we should say what's going on.

```suggestion
	// Set max to a high value, e.g. so that Test_stdio_large can pass
	parsed.MemorySection.Max = 1024 // 64MB
```

**Review by codefromthecrypt — APPROVED** [review]
I'm glad you did this in unit tests, not in the main tree. Cheers!
