### PR TITLE
fs: nonblocking writes should use syscall.Write

### LINKED ISSUE #1538: Non-blocking stdio isn't working correctly
**Describe the bug**

Non-blocking stdio isn't working correctly.

**To Reproduce**

Use [`gotip`](https://pkg.go.dev/golang.org/dl/gotip) that includes at least https://github.com/golang/go/commit/13529cc5f443ef4e242da3716daa0032aa8d34f2 (note that this will be part of the Go 1.21 release in ~August).

If I compile the following module:

```go
package main

import (
	"io"
	"os"
	"time"
)

func main() {
	go func() {
		time.Sleep(1 * time.Second)
		os.Stdout.WriteString("waiting for stdin...\n")
	}()

	b, err := io.ReadAll(os.Stdin)
	if err != nil {
		panic(err)
	}
	os.Stdout.Write(b)
	return
}
```

using:

```
$ GOOS=wasip1 GOARCH=wasm gotip build -o stdio.wasm stdio.go
```

and then run the script with wazero, it returns errno=28 (EINVAL) from `poll_oneoff` which causes Go to crash:

```
$ (sleep 3; echo foo) | wazero run stdio.wasm 
waiting for stdin...
errno= 28  len(pollsubs)= 1
fatal error: poll_oneoff failed

runtime stack:
runtime.throw({0x17c29, 0x12})
	/Users/chris/sdk/gotip/src/runtime/panic.go:1077 +0x3 fp=0xeb778 sp=0xeb750 pc=0x12250003
runtime.netpoll(0xffffffffffffffff)
	/Users/chris/sdk/gotip/src/runtime/netpoll_wasip1.go:218 +0x45 fp=0xeb7e8 sp=0xeb778 pc=0x11f30045
```

**Expected behavior**

[wasi-go](https://github.com/stealthrocket/wasi-go) does the right thing here:

```
$ (sleep 3; echo foo) | wasirun stdio.wasm                  
waiting for stdin...
foo
```

**Environment (please complete the relevant information):**

```
$ gotip version
go version devel go1.21-13529cc Tue Jun 27 01:09:18 2023 +0000 darwin/arm64
$ uname -a
Darwin MBP.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64
$ wazero version
v1.2.1
```

### PR DESCRIPTION
**Pull request by evacchi**
resolves #1538 on non-Windows platforms. Windows will be addressed in #1579.

Using blocking `file.Write` APIs together with nonblocking I/O, causes stdout corruption under certain conditions. 

In particular, a reliable way to reproduce the issue is to capture the stdout of a sub-process running wazero. This PR fixes the writing issue by introducing `writeFd` (similar to `readFd` introduced in #1517), a function that just invokes the syscall directly when I/O is non-blocking. 

It also introduces the constants `nonBlockingFileReadSupported`, `nonBlockingFileWriteSupported`, superseding the generic `nonBlockingFileIoSupported`: the reason is still related to #1579, where Windows-related concerns will be addressed; for now we ignore the issue on that platform. However, because the test is _not skipped_ on Windows, it looks like that platform is not affected (also verified on my Windows machine).

### CODE REVIEW

File: internal/sysfs/file_unix.go [hunk 1]
```diff
@@ -19,3 +19,13 @@ func readFd(fd uintptr, buf []byte) (int, syscall.Errno) {
 	errno := platform.UnwrapOSError(err)
 	return n, errno
 }
+
+// writeFd exposes syscall.Write.
```
Comment (codefromthecrypt) [inline internal/sysfs/file_unix.go:23]: this is a pretty cool way to ensure the logic is shared. nice!

Comment (evacchi) [reply internal/sysfs/file_unix.go:23]: (actually I though you did this first...)

Comment (codefromthecrypt) [reply internal/sysfs/file_unix.go:23]: uhh anyway thanks 😎

File: internal/sysfs/file_unix.go [hunk 2]
```diff
@@ -19,3 +19,13 @@ func readFd(fd uintptr, buf []byte) (int, syscall.Errno) {
...
+func writeFd(fd uintptr, buf []byte) (int, syscall.Errno) {
+	if len(buf) == 0 {
+		return 0, 0 // Short-circuit 0-len reads.
```
Comment (ydnar) [inline internal/sysfs/file_unix.go:26]: Reads?

File: internal/sysfs/osfile.go [hunk 3]
```diff
@@ -213,7 +213,12 @@ func (f *osFile) Readdir(n int) (dirents []fsapi.Dirent, errno syscall.Errno) {
 
 // Write implements the same method as documented on fsapi.File
 func (f *osFile) Write(buf []byte) (n int, errno syscall.Errno) {
-	if n, errno = write(f.file, buf); errno != 0 {
+	if len(buf) == 0 {
+		return 0, 0 // Short-circuit 0-len reads.
```
Comment (ydnar) [inline internal/sysfs/osfile.go:217]: Reads?

**Review by ydnar — CHANGES_REQUESTED** [review]

File: internal/sysfs/file_unix.go (hunk 2 above)
Comment (evacchi) [reply internal/sysfs/file_unix.go:26]: heh, lazy copypaste :)

**Comment by evacchi** [comment]
the windows failure I know to handle (i.e. for now nothing, I'll include the fix in #1579)

File: imports/wasi_snapshot_preview1/testdata/gotip/wasi.go [hunk 4]
```diff
@@ -259,3 +264,46 @@ func mainStdin() error {
 func mainStdout() {
 	os.Stdout.WriteString("test")
 }
+
+func mainLargeStdout() {
```
Comment (evacchi) [inline imports/wasi_snapshot_preview1/testdata/gotip/wasi.go:268]: this is the same test as [bug449.go](https://github.com/golang/go/blob/b88bd917b8dd8aabc471b1de41b3ee8c0d6eeabe/test/fixedbugs/bug449.go) except here it doesn't show the issue, because I cannot reproduce the same exact setup. I think the trick is that the test case in the Go repo is run via `exec` on a `wazero` binary, while here we are instantiating wazero without forking.

Comment (evacchi) [reply imports/wasi_snapshot_preview1/testdata/gotip/wasi.go:268]: resolved by actually forking

**Review by mathetake — APPROVED** [review]
