### PR TITLE
threads: close shared memory with store, not child modules

### LINKED ISSUE #1936: flaky test: in ExampleCoreFeaturesThreads
cc @anuraaga @ncruces 

https://github.com/tetratelabs/wazero/actions/runs/7617746876/job/20747441295?pr=1935
https://github.com/tetratelabs/wazero/actions/runs/7614493794/job/20736874840?pr=1926

The test causes segv occasionally 

```
unexpected fault address 0x7fa6bc2fb480
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fa6bc2fb480 pc=0x7fa6bc32c292]

goroutine 29 [running]:
runtime.throw({0x6d899d?, 0x8d53f8?})
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/panic.go:1047 +0x5d fp=0xc000428cf8 sp=0xc000428cc8 pc=0x438edd
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/signal_unix.go:846 +0x2c5 fp=0xc000428d48 sp=0xc000428cf8 pc=0x44f965
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).execWasmFunction(0xc00043e870, {0x739908, 0xc0000b2000}, 0xc00021d590?)
	/home/runner/work/wazero/wazero/internal/engine/compiler/engine.go:1049 +0xa5 fp=0xc000428dc8 sp=0xc000428d48 pc=0x5d4bc5
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).call(0xc00043e870, {0x739908, 0xc0000b2000}, {0x0?, 0x5d33ff?, 0x0?}, {0x0, 0x0, 0x0})
	/home/runner/work/wazero/wazero/internal/engine/compiler/engine.go:790 +0x27e fp=0xc000428e98 sp=0xc000428dc8 pc=0x5d39de
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).Call(0xc00043e870?, {0x739908?, 0xc0000b2000?}, {0x0?, 0x0?, 0x0?})
	/home/runner/work/wazero/wazero/internal/engine/compiler/engine.go:742 +0x10b fp=0xc000428f10 sp=0xc000428e98 pc=0x5d370b
github.com/tetratelabs/wazero/experimental_test.ExampleCoreFeaturesThreads.func1()
	/home/runner/work/wazero/wazero/experimental/features_example_test.go:75 +0x16b fp=0xc000428fe0 sp=0xc000428f10 pc=0x63590b
runtime.goexit()
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000428fe8 sp=0xc000428fe0 pc=0x46ba41
created by github.com/tetratelabs/wazero/experimental_test.ExampleCoreFeaturesThreads
	/home/runner/work/wazero/wazero/experimental/features_example_test.go:66 +0x4cb
```

### PR DESCRIPTION
**Pull request by anuraaga**
When porting code, I thought I was cleaning things up by putting in the nicely named "ensure resources closed" method but just broke it... That function is called when child modules are closed so can't be responsible for memory closing.

Fixes #1936

### CODE REVIEW

File: experimental/features_example_test.go [hunk 1]
```diff
@@ -71,7 +71,7 @@ func ExampleCoreFeaturesThreads() {
 			// among arbitrary goroutine invocations.
 			child := createChildModule(r, mod, wasmCompiled)
 			fn := child.mod.ExportedFunction("run")
-			for i := 0; i < 6000; i++ {
+			for i := 0; i < 100000; i++ {
```
Comment (anuraaga) [inline experimental/features_example_test.go:74]: I went ahead and raised to a point where interpreter takes about 1s on my machine. What do you think?

File: internal/engine/compiler/engine.go [hunk 2]
```diff
@@ -1151,8 +1151,16 @@ func (ce *callEngine) builtinFunctionMemoryGrow(mem *wasm.MemoryInstance) {
 
 	// Update the moduleContext fields as they become stale after the update ^^.
 	bufSliceHeader := (*reflect.SliceHeader)(unsafe.Pointer(&mem.Buffer))
-	ce.moduleContext.memorySliceLen = uint64(bufSliceHeader.Len)
-	ce.moduleContext.memoryElement0Address = bufSliceHeader.Data
+	if mem.Shared {
+		// Use atomic to ensure visibility for good measure. Though in practice, we know
```
Comment (anuraaga) [inline internal/engine/compiler/engine.go:1155]: This I just found when comparing the two repos. As per this comment, it's likely not a big deal but kept it just to have a "best practice" of always using atomic writes in shared mode, I can revert if not needed though

Comment (ncruces) [reply internal/engine/compiler/engine.go:1155]: I'm getting a bit uneasy about all these atomic stores that don't seem to have corresponding atomic loads.

I know the loads are in assembly, and the amd64 versions are probably safe (atomic stores have an mfence, or xchg instruction, loads don't, apparently) but I'm not sure about arm64.

Did you see how Go implements atomic, on godbolt or similar?

Comment (anuraaga) [reply internal/engine/compiler/engine.go:1155]: I had assumed Go's implementation but indeed hadn't verified it. Just checked, luckily they're pretty straight forward

https://github.com/golang/go/blob/adead1a93f472affa97c494ef19f2f492ee6f34a/src/runtime/internal/atomic/atomic_arm64.s#L120

STLR, same as what we use

https://github.com/tetratelabs/wazero/blob/7d5b6739da3ae7456db41399a2701e22d66b57c4/internal/engine/compiler/impl_threads_arm64.go#L127

For reading with its sister instruction, LDAR

https://github.com/tetratelabs/wazero/blob/7d5b6739da3ae7456db41399a2701e22d66b57c4/internal/engine/compiler/impl_arm64.go#L4052

Does it seem ok?

Comment (anuraaga) [reply internal/engine/compiler/engine.go:1155]: For good measure, amd64, store is xchg as we do

https://github.com/golang/go/blob/adead1a93f472affa97c494ef19f2f492ee6f34a/src/runtime/internal/atomic/atomic_amd64.s#L174

and load is just normal load same as we do too

https://github.com/golang/go/blob/adead1a93f472affa97c494ef19f2f492ee6f34a/src/runtime/internal/atomic/atomic_amd64.go#L30

Comment (ncruces) [reply internal/engine/compiler/engine.go:1155]: Right, ignore me, I guess I missed the A in `LARD` [here](https://github.com/tetratelabs/wazero/blob/6166dae7410790a087487063384c501639ec2139/internal/engine/compiler/impl_arm64.go#L4052).

**Review by ncruces — APPROVED** [review]

**Review by mathetake — APPROVED** [review]
