### PR TITLE
Complete baseline JIT WebAssembly compiler for amd64 target.

### LINKED ISSUE #65: Tracking issue for the baseline JIT engine for amd64 target
## Baseline JIT engine
- Stack hight checks (https://github.com/tetratelabs/wazero/pull/68)
- Implement all the Instructions
    - https://github.com/tetratelabs/wazero/pull/70
    - https://github.com/tetratelabs/wazero/pull/71
    - https://github.com/tetratelabs/wazero/pull/73
    - https://github.com/tetratelabs/wazero/pull/81
    - https://github.com/tetratelabs/wazero/pull/82
    - https://github.com/tetratelabs/wazero/pull/85
    - https://github.com/tetratelabs/wazero/pull/86
    - https://github.com/tetratelabs/wazero/pull/89
    - https://github.com/tetratelabs/wazero/pull/93
    - https://github.com/tetratelabs/wazero/pull/96
    - https://github.com/tetratelabs/wazero/pull/97
    - https://github.com/tetratelabs/wazero/pull/99
    - https://github.com/tetratelabs/wazero/pull/103
    - https://github.com/tetratelabs/wazero/pull/111
    - https://github.com/tetratelabs/wazero/pull/113
    - https://github.com/tetratelabs/wazero/pull/116
    - https://github.com/tetratelabs/wazero/pull/118
    - https://github.com/tetratelabs/wazero/pull/119
    - https://github.com/tetratelabs/wazero/pull/121
    - https://github.com/tetratelabs/wazero/pull/124
    - https://github.com/tetratelabs/wazero/pull/126
    - https://github.com/tetratelabs/wazero/pull/132
    - https://github.com/tetratelabs/wazero/pull/141 for br_table
 
- basic stack trace: https://github.com/tetratelabs/wazero/pull/70 
- Pass spectests
    - https://github.com/tetratelabs/wazero/pull/127
    - https://github.com/tetratelabs/wazero/pull/141

## Post baseline
- achieve function calls without going back to Go code (`engine.exec`)
- Adds tests and better documentations on mmap system calls (See https://github.com/tetratelabs/wazero/pull/60#discussion_r765449928)
- Bunch of optimizations! (not limited to single pass)

### PR DESCRIPTION
**Pull request by mathetake**
This commit completes the baseline (singlepass) JIT WebAssembly compiler
for amd64 target with the implementation for br_table instruction.

The implementation passes 100% of WebAssembly specification test, 
 just like our interpreter. This is the world's first JIT compilation engine purely 
written in Go, and the implementation is stable under multple goroutines, and 
never broken by Go runtime. The JIT engine is tested both for Linux and Darwin.

Even though this passes the spectests and is implemented as "JIT", our calling convention 
proxies all function calls though non-native Go world, therefore there's some performance 
overhead. This would be fixed in a following commit which allows us to make function calls
in the fully native way. See https://github.com/tetratelabs/wazero/pull/60 and RATIONALE.md for design details. 

resolves #65 #42

### CODE REVIEW

**Comment by mathetake** [comment]
I will mark this ready after adding more docs, but anyway now JIT compiler passes 100% of spectest!

**Comment by codefromthecrypt** [comment]
image

**Comment by huttarichard** [comment]
@mathetake this is absolutely excellent work Mathew, kudos.

File: bench/bench_test.go [hunk 1]
```diff
@@ -20,6 +21,11 @@ func BenchmarkEngines(b *testing.B) {
 		setUpStore(store)
 		runAllBenches(b, store)
 	})
+	b.Run("jit", func(b *testing.B) {
```
Comment (codefromthecrypt) [inline bench/bench_test.go:24]: 🚀

File: wasm/jit/engine.go [hunk 2]
```diff
@@ -319,6 +330,8 @@ func (f *compiledFunction) isHostFunction() bool {
 const (
 	builtinFunctionAddressMemoryGrow wasm.FunctionAddress = iota
 	builtinFunctionAddressMemorySize
+	// builtinFunctionAddressBreakPoint is only for wazero developers. Disabled by default.
```
Comment (codefromthecrypt) [inline wasm/jit/engine.go:333]:
```suggestion
	// builtinFunctionAddressBreakPoint is internal (only for wazero developers). Disabled by default.
```

File: wasm/jit/jit_amd64.go [hunk 3]
```diff
@@ -452,8 +483,12 @@ func (c *amd64Compiler) compileBr(o *wazeroir.OperationBr) error {
 	if err := c.maybeMoveTopConditionalToFreeGeneralPurposeRegister(); err != nil {
 		return err
 	}
+	return c.branchInto(o.Target)
+}
 
-	if o.Target.IsReturnTarget() {
+// branchInto adds instruction necessary to jump into the given branch target.
```
Comment (codefromthecrypt) [inline wasm/jit/jit_amd64.go:489]: I think it is fine to not prefix with compile because the param isn't an operation

File: wasm/jit/jit_amd64.go [hunk 4]
```diff
@@ -633,8 +670,216 @@ func (c *amd64Compiler) compileBrIf(o *wazeroir.OperationBrIf) error {
 	return nil
 }
 
+// compileBrTable adds instructions to do br_table operation.
+// A br_table operation has list of targets and default target, and
+// this pops a value from the stack (called "index") and decide which branch we go into next
+// based on the value.
+// For example, assume we have operations like {default: L_DEFAULT, targets: [L0, L1, L2]}.
```
Comment (codefromthecrypt) [inline wasm/jit/jit_amd64.go:677]:
```suggestion
//
// For example, assume we have operations like {default: L_DEFAULT, targets: [L0, L1, L2]}.
```

File: wasm/jit/jit_amd64.go [hunk 5]
```diff
@@ -633,8 +670,216 @@ func (c *amd64Compiler) compileBrIf(o *wazeroir.OperationBrIf) error {
...
+// If "index" >= len(defaults), then branch into the L_DEFAULT label.
+// Othewise, we enter label of targets[index].
 func (c *amd64Compiler) compileBrTable(o *wazeroir.OperationBrTable) error {
-	panic("TODO implement!")
+	index := c.locationStack.pop()
+
+	// If the operation doesn't have target but default,
+	// we just branch into the default label and do early return.
```
Comment (codefromthecrypt) [inline wasm/jit/jit_amd64.go:684]:
```suggestion
	// branch into the default label and return early.
```

File: wasm/jit/jit_amd64.go [hunk 6]
```diff
@@ -633,8 +670,216 @@ func (c *amd64Compiler) compileBrIf(o *wazeroir.OperationBrIf) error {
...
+	if len(o.Targets) == 0 {
+		c.locationStack.releaseRegister(index)
+		if err := c.emitDropRange(o.Default.ToDrop); err != nil {
+			return err
+		}
+		return c.branchInto(o.Default.Target)
+	}
+
+	// Otherwise, we jump into the selected branch.
+
```
Comment (codefromthecrypt) [inline wasm/jit/jit_amd64.go:694]:
```suggestion
```

File: wasm/jit/jit_amd64.go [hunk 7]
```diff
@@ -633,8 +670,216 @@ func (c *amd64Compiler) compileBrIf(o *wazeroir.OperationBrIf) error {
...
+	// in the branch table relative to the next instruction (calcAbsoluteAddressOfSelectedLabel) stored in RIP register.
+	readRIP.From.Offset = 0xffff
+	// Since the assembler cannot directly emit "LEA foo [rip + bar]", we use the some hack here:
+	// We intentionally use x86.REG_BP here so that the resulting instruction sequence becomes
+	// exactly the same as "LEA foo [rip + bar]" except the most significant bit of the third byte.
+	// We do the rewrite in onGenerateCallbacks which is invoked after the assembler emitted the code.
+	readRIP.From.Reg = x86.REG_BP
+	c.addInstruction(readRIP)
+
+	// Now we have the address of L0 in tmp register, and the offset to the target label in the index.register.
```
Comment (codefromthecrypt) [inline wasm/jit/jit_amd64.go:803]: great comments in this function. look like a lot of research

File: wasm/jit/jit_amd64.go [hunk 8]
```diff
@@ -661,40 +906,63 @@ func (c *amd64Compiler) assignJumpTarget(labelKey string, jmpInstruction *obj.Pr
 	}
 }
 
-func (c *amd64Compiler) compileLabel(o *wazeroir.OperationLabel) error {
+// compileLabel initiates the given label's machine code generation, and emit the
+// NOP instruction as a initial one so that bracnh operations can target it without
```
Comment (codefromthecrypt) [inline wasm/jit/jit_amd64.go:910]:
```suggestion
// NOP instruction as a initial one so that branch operations can target it without
```

**Review by codefromthecrypt — APPROVED** [review]
fantastico.. I'm excited not only tests pass, but benchmarks execute without a snag!

File: wasm/jit/jit_amd64.go [hunk 9]
```diff
@@ -156,11 +164,27 @@ func (c *amd64Compiler) emitPreamble() {
 	c.initializeReservedRegisters()
 }
 
-func (c *amd64Compiler) generate() ([]byte, uint64, error) {
-	code, err := mmapCodeSegment(c.builder.Assemble())
+func (c *amd64Compiler) generate() (code []byte, staticData [][]byte, maxStackPointer uint64, err error) {
```
Comment (codefromthecrypt) [inline wasm/jit/jit_amd64.go:167]:
```suggestion
func (c *amd64Compiler) generate() (code []byte, staticData compiledFunctionStaticData, maxStackPointer uint64, err error) {
```

**Comment by mathetake** [comment]
img

**Comment by mathetake** [comment]
I can't believe I've done this in less than 2 months!

**Comment by codefromthecrypt** [comment]
If you don't, well whoever your hijacked your GitHub account did it in less than 2 months, then

**Comment by huttarichard** [comment]
You guys are f legends.
